[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dnspython==2.7.0",
    "flask==3.1.0",
    "flask-httpauth==4.8.0",
    "pymongo==4.11.1",
    "werkzeug==3.1.3",
]
